### ISSUE TITLE
Game crashes on first turn

### ISSUE THREAD

**Issue by islamelnabarawy** [jbradberry/connect-four#1]
The socketplayer crashes on the first turn when attempting to play connect-four with the following error:
```
# board-play.py connect_four jrb.mcts.uct -e time=5
You are player #1.
Traceback (most recent call last):
  File "boardgame-socketplayer/bin/board-play.py", line 37, in <module>
    client.run()
  File "boardgame-socketplayer/boardplayer/player.py", line 33, in run
    self.receiver[data['type']](data)
  File "boardgame-socketplayer/boardplayer/player.py", line 55, in handle_update
    print self.player.display(state, action)
  File "mcts/mcts/uct.py", line 37, in display
    action = self.board.pack_action(action)
  File "connect-four/connect_four/connectfour.py", line 61, in pack_action
    return int(notation)
ValueError: invalid literal for int() with base 10: ''
```

**Comment by jbradberry** [comment]
@islamelnabarawy hi, sorry to be so neglectful about this.  Can you confirm whether or not this is still an issue for you?  The last couple of times I've made changes I've run through a couple of games with the human and AI players without experiencing this bug, so it may have already been taken care of by other changes.

**Comment by islamelnabarawy** [comment]
True, I'm no longer able to reproduce it. Thanks for following up!
